[project]
name = "highload-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.17.0",
    "asyncio>=4.0.0",
    "asyncpg>=0.30.0",
    "dishka>=1.7.2",
    "fastapi-users[sqlalchemy]>=14.0.1",
    "fastapi[users]>=0.119.0",
    "pydantic>=2.12.2",
    "pydantic-settings>=2.11.0",
    "pyjwt>=2.10.1",
    "python-logstash-async>=4.0.2",
    "uvicorn>=0.37.0",
    "taskiq[redis]>=0.11.0",
    "taskiq-redis>=0.6.0",
    "redis>=5.0.0",
]
