"""add location type

Revision ID: 2fef63fea91e
Revises: 21a91f77c1ce
Create Date: 2025-09-26 00:18:56.849884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fef63fea91e'
down_revision: Union[str, Sequence[str], None] = '21a91f77c1ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    locationtype = postgresql.ENUM('WAREHOUSE', 'TRADING_POINT', name='locationtype')
    locationtype.create(op.get_bind())
    op.add_column('locations', sa.Column('location_type', sa.Enum('WAREHOUSE', 'TRADING_POINT', name='locationtype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'location_type')
    # ### end Alembic commands ###
