"""remove order 

Revision ID: 60bc84c05dc2
Revises: b38424610a87
Create Date: 2025-09-25 23:35:14.592614

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '60bc84c05dc2'
down_revision: Union[str, Sequence[str], None] = 'b38424610a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
