"""empty message

Revision ID: 8a4c2f8de6fb
Revises: 3edb6f40231e
Create Date: 2025-12-22 06:39:23.313403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a4c2f8de6fb'
down_revision: Union[str, Sequence[str], None] = '3edb6f40231e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'threshold')
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('threshold', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
