"""fix relationships

Revision ID: c38bd650e864
Revises: 60bc84c05dc2
Create Date: 2025-09-25 23:41:08.193906

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'c38bd650e864'
down_revision: Union[str, Sequence[str], None] = '60bc84c05dc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
